%YAML:1.0

######################################## Boards Parameters ###################################################
number_x_square: 7  #number of squares in the X direction
number_y_square: 5  #number of squares the Y direction
resolution_x: 700  # horizontal resolution in pixel
resolution_y: 500  # vertical resolution in pixel
length_square: 4  # parameters on the marker (can be kept as it is)
length_marker: 1  # parameters on the marker (can be kept as it is)
number_board: 26 # number of boards used for calibration (for overlapping camera 1 is enough ...)
boards_index: [93, 94, 96, 101, 102, 103, 110, 111, 112, 113, 150, 151, 152, 153, 154, 155, 156, 157, 181, 191, 183, 176, 180, 184, 189, 187] #leave it empty [] if the board index are ranging from zero to number_board
# example of usage boards_index: [5,10] <-- only two board with index 5/10
square_size: 3.75  # size of each square of the board in cm/mm/whatever you want

board_kind: 1


############# Boards Parameters for different board size (leave empty if all boards have the same size) #################
number_x_square_per_board: [7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 5, 5, 5, 5, 5, 5, 5, 5, 3, 3, 3, 3, 3, 3, 3, 3]
number_y_square_per_board: [5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]
square_size_per_board: [15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 21.4, 21.4, 21.4, 21.4, 21.4, 21.4, 21.4, 21.4, 7.5, 7.5, 7.5, 7.5, 7.5, 7.5, 7.5, 7.5]
board_kind_per_board: []

######################################## Camera Parameters ###################################################
distortion_model: 0 #0:Brown (perspective) // 1: Kannala (fisheye)
distortion_per_camera : [] #specify the model per camera, 
#leave "distortion_per_camera" empty [] if they all follow the same model (make sure that the vector is as long as cameras nb)
number_camera: 7  # number of cameras in the rig to calibrate
refine_corner: 0  # activate or deactivate the corner refinement
min_perc_pts: 0.5  # min percentage of points visible to assume a good detection

cam_params_path: "../../data/221011_42dot_caldata/niro_2k_data3/calibrated_cameras_data2.yml" # "../../Images_Plan/calibrated_cameras_data.yml"  # file with cameras intrinsics to initialize the intrinsic, write "None" if no initialization available 
fix_intrinsic: 1 #if 1 then the intrinsic parameters will not be estimated nor refined (initial value needed)

######################################## Object ###################################################
# object_data: "../../data/221011_42dot_caldata/niro_2k_multi/calibrated_objects_data.yml"
fix_object: 0

######################################## Images Parameters ###################################################
root_path: "../../data/221011_42dot_caldata/niro_2k_data3/" #"../../Images_Sim1Cam3Board/" # "../../Images_NonOver3/"  "../../Images_Cube/" "../../Images_Plan/" "../../Images_NonOver6Cam/"
#root_path: "../../Data/bus/"
cam_prefix: "Cam_"

######################################## Optimization Parameters ###################################################
ransac_threshold: 10 #RANSAC threshold in pixel (keep it high just to remove strong outliers)
number_iterations: 1000 #Max number of iterations for the non linear refinement

######################################## Hand-eye method #############################################
he_approach: 0 #0: bootstrapped he technique, 1: traditional he

######################################## Output Parameters ###################################################
save_path: "../../data/calibrated_Niro2k_3/"
save_detection: 1
save_reprojection: 1
camera_params_file_name: ""
